name: youtubedl
description: youtube-dl as a fully featured mobile app
publish_to: 'none' # Remove this line if you wish to publish to pub.devP
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

flutter:
  uses-material-design: true
  assets:
    - translations/

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  auto_route: ^0.6.7
  provider: ^4.3.2
  injectable: ^1.0.4
  get_it: ^4.0.4
  flutter_ffmpeg: ^0.2.10
  division: ^0.8.8
  super_enum: ^0.4.2
  better_enum: ^1.0.0
  file_picker: ^1.13.3
  flutter_bloc: ^6.0.1
  equatable: ^1.2.3
  shared_preferences: ^0.5.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: null
  auto_route_generator: ^0.6.8
  injectable_generator: ^1.0.4
  mockito: ^4.1.1
  super_enum_generator: ^0.5.0

